lsi: false
safe: false
title: מבנה נתונים התשפו
description: אתר המכיל את המצגות 
# theme: the-plain
plugins:
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain

source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
