lsi: false
safe: false
title: מבנה נתונים התשפו
description: אתר המכיל את המצגות 
theme: minima
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
